<?php

namespace Proxies\__CG__\projetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Eleve extends \projetBundle\Entity\Eleve implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'paiement', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'groupe', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'dateNaissanceEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'clubs', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'parent', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'sexeEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'niveauEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'nomEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'prenomEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'matriculeEleve');
        }

        return array('__isInitialized__', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'paiement', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'groupe', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'dateNaissanceEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'clubs', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'parent', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'sexeEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'niveauEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'nomEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'prenomEleve', '' . "\0" . 'projetBundle\\Entity\\Eleve' . "\0" . 'matriculeEleve');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Eleve $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPaiement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', array());

        return parent::getPaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiement($paiement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiement', array($paiement));

        return parent::setPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupe', array());

        return parent::getGroupe();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupe($groupe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupe', array($groupe));

        return parent::setGroupe($groupe);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent($parent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getClubs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClubs', array());

        return parent::getClubs();
    }

    /**
     * {@inheritDoc}
     */
    public function setClubs($clubs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClubs', array($clubs));

        return parent::setClubs($clubs);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissanceEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissanceEleve', array());

        return parent::getDateNaissanceEleve();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissanceEleve($dateNaissanceEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissanceEleve', array($dateNaissanceEleve));

        return parent::setDateNaissanceEleve($dateNaissanceEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveauEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveauEleve', array());

        return parent::getNiveauEleve();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveauEleve($niveauEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveauEleve', array($niveauEleve));

        return parent::setNiveauEleve($niveauEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexeEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexeEleve', array());

        return parent::getSexeEleve();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexeEleve($sexeEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexeEleve', array($sexeEleve));

        return parent::setSexeEleve($sexeEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEleve($nomEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEleve', array($nomEleve));

        return parent::setNomEleve($nomEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEleve', array());

        return parent::getNomEleve();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomEleve($prenomEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomEleve', array($prenomEleve));

        return parent::setPrenomEleve($prenomEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomEleve', array());

        return parent::getPrenomEleve();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculeEleve($matriculeEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculeEleve', array($matriculeEleve));

        return parent::setMatriculeEleve($matriculeEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculeEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculeEleve', array());

        return parent::getMatriculeEleve();
    }

}
