<?php

namespace Proxies\__CG__\projetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personnel extends \projetBundle\Entity\Personnel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'id', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'poste', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'nomPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'prenomPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'numTelPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'adressePersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'cinPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'loginPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'passwordPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'emailPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'matriculePersonnel');
        }

        return array('__isInitialized__', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'id', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'poste', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'nomPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'prenomPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'numTelPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'adressePersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'cinPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'loginPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'passwordPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'emailPersonnel', '' . "\0" . 'projetBundle\\Entity\\Personnel' . "\0" . 'matriculePersonnel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personnel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste', array());

        return parent::getPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoste($poste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoste', array($poste));

        return parent::setPoste($poste);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPersonnel($nomPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPersonnel', array($nomPersonnel));

        return parent::setNomPersonnel($nomPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPersonnel', array());

        return parent::getNomPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomPersonnel($prenomPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomPersonnel', array($prenomPersonnel));

        return parent::setPrenomPersonnel($prenomPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomPersonnel', array());

        return parent::getPrenomPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTelPersonnel($numTelPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTelPersonnel', array($numTelPersonnel));

        return parent::setNumTelPersonnel($numTelPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTelPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTelPersonnel', array());

        return parent::getNumTelPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePersonnel($adressePersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePersonnel', array($adressePersonnel));

        return parent::setAdressePersonnel($adressePersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePersonnel', array());

        return parent::getAdressePersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinPersonnel($cinPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinPersonnel', array($cinPersonnel));

        return parent::setCinPersonnel($cinPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinPersonnel', array());

        return parent::getCinPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginPersonnel($loginPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginPersonnel', array($loginPersonnel));

        return parent::setLoginPersonnel($loginPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginPersonnel', array());

        return parent::getLoginPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordPersonnel($passwordPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordPersonnel', array($passwordPersonnel));

        return parent::setPasswordPersonnel($passwordPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordPersonnel', array());

        return parent::getPasswordPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailPersonnel($emailPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailPersonnel', array($emailPersonnel));

        return parent::setEmailPersonnel($emailPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailPersonnel', array());

        return parent::getEmailPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculePersonnel($matriculePersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculePersonnel', array($matriculePersonnel));

        return parent::setMatriculePersonnel($matriculePersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculePersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculePersonnel', array());

        return parent::getMatriculePersonnel();
    }

}
