<?php

namespace Proxies\__CG__\projetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PersonnelAdministratif extends \projetBundle\Entity\PersonnelAdministratif implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'id', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'matriculePa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'nomPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'prenomPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'numTelPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'adressePa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'cinPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'loginPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'passwordPa');
        }

        return array('__isInitialized__', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'id', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'matriculePa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'nomPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'prenomPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'numTelPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'adressePa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'cinPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'loginPa', '' . "\0" . 'projetBundle\\Entity\\PersonnelAdministratif' . "\0" . 'passwordPa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PersonnelAdministratif $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculePa($matriculePa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculePa', array($matriculePa));

        return parent::setMatriculePa($matriculePa);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculePa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculePa', array());

        return parent::getMatriculePa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPa($nomPa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPa', array($nomPa));

        return parent::setNomPa($nomPa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPa', array());

        return parent::getNomPa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomPa($prenomPa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomPa', array($prenomPa));

        return parent::setPrenomPa($prenomPa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomPa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomPa', array());

        return parent::getPrenomPa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTelPa($numTelPa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTelPa', array($numTelPa));

        return parent::setNumTelPa($numTelPa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTelPa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTelPa', array());

        return parent::getNumTelPa();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePa($adressePa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePa', array($adressePa));

        return parent::setAdressePa($adressePa);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePa', array());

        return parent::getAdressePa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinPa($cinPa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinPa', array($cinPa));

        return parent::setCinPa($cinPa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinPa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinPa', array());

        return parent::getCinPa();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginPa($loginPa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginPa', array($loginPa));

        return parent::setLoginPa($loginPa);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginPa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginPa', array());

        return parent::getLoginPa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordPa($passwordPa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordPa', array($passwordPa));

        return parent::setPasswordPa($passwordPa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordPa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordPa', array());

        return parent::getPasswordPa();
    }

}
