<?php

namespace projetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CahierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CahierRepository extends EntityRepository
{
}
