<?php

namespace projetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EleveGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveGroupeRepository extends EntityRepository
{
}
