<?php

namespace projetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiRepository extends EntityRepository
{
}
