<?php

namespace projetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypePaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePaiementRepository extends EntityRepository
{
}
